project_id = "khpqamukrduodzefzcmm"

[functions.assign-role]
verify_jwt = false

[functions.ai-project-assistant]
verify_jwt = false

[functions.import-project-doc]
verify_jwt = false

[functions.import-projects-bulk]
verify_jwt = false
